In [30]:
# testing 123
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

# mengambil datanya
df = pd.read_csv("train.csv")
dft = pd.read_csv("test.csv")

print("berhasil mengambil datanya....")

berhasil mengambil datanya....

In [31]:
# memisahkan dengan train test split
X = df.drop(['SalePrice'], axis=1)
y = df.SalePrice
X_train_full, X_test_full, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# display(X.head())
display(X_train_full.head())

      Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
618  619          20       RL  ...    2007       New       Partial
870  871          20       RL  ...    2009        WD        Normal
92    93          30       RL  ...    2009        WD        Normal
817  818          20       RL  ...    2008        WD        Normal
302  303          20       RL  ...    2006        WD        Normal

[5 rows x 80 columns]

In [32]:
# memisahkan data category dan data numerical
object_cols = X_train_full.select_dtypes(include='object')
category_cols = [cname for cname in object_cols if
                  X_train_full[cname].nunique() < 10]

# print(category_cols)
# ambil numerical cols
numerical_cols = [cname for cname in X_train_full if X_train_full[cname].dtypes in ['int64', 'float64']]
print("Numerical cols nya adalah")
# print(numerical_cols)
# berhasil mendapatkan categorical dan numerical

Numerical cols nya adalah

C:\Users\HP\AppData\Local\Temp\ipykernel_23248\1569231211.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = X_train_full.select_dtypes(include='object')

In [33]:
# mengcopy filenya dan mengidentifikasi dengan full
all_cols = category_cols + numerical_cols
X_train = X_train_full[all_cols].copy()
X_valid = X_test_full[all_cols].copy()
X_test = dft[all_cols].copy()

X_train.head()

    MSZoning Street Alley LotShape  ... PoolArea MiscVal MoSold YrSold
618       RL   Pave   NaN      Reg  ...        0       0      7   2007
870       RL   Pave   NaN      Reg  ...        0       0      8   2009
92        RL   Pave  Grvl      IR1  ...        0       0      8   2009
817       RL   Pave   NaN      IR1  ...        0       0      7   2008
302       RL   Pave   NaN      IR1  ...        0       0      1   2006

[5 rows x 77 columns]

In [35]:
# selanjutnya lakukan pipeline model
# preprocessing menggunakan pipeline
# preprocessing numerical data
numerical_transformer = SimpleImputer(strategy='constant')

# jadi untuk numerical cukup di simple imputer saja
categorical_transformer = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(
        handle_unknown='ignore'
    ))
])

# berhasil membuat modelnya
# bundle processing for numerical and categorical
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('category', categorical_transformer, category_cols)
    ]
)

print("Berhasil membuat mesin preprocessing")

Berhasil membuat mesin preprocessing

In [36]:
# membuat mesin model
model = RandomForestRegressor(n_estimators=200, random_state=42)

In [37]:
# membuat pipeline modelnya
from sklearn.metrics import mean_absolute_error
my_pipe = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('model', model)
])

# preprocess training data dan fit modelnya
my_pipe.fit(X_train, y_train)

# melakukan prediksi
prediction_train = my_pipe.predict(X_valid)
print("berhasil melakukan prediksi")
score_mae = mean_absolute_error(y_test, prediction_train)
print(f"Score MAE nya adalah : {score_mae}")

berhasil melakukan prediksi
Score MAE nya adalah : 17533.871746575343